version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql-logger
    restart: always
    environment:
      DB_ROOT_PASSWORD: rootpassword
      DB_DATABASE: log_system
      DB_USER: log_user
      DB_PASSWORD: logpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: fastify-backend
    restart: always
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: mysql-logger
      DB_USER: log_user
      DB_PASSWORD: logpassword
      DB_DATABASE: log_system
      DB_PORT: 3306
      RABBITMQ_URL: amqp://rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data:
